/**
 * Initial content mirrored from the original frontend data files.
 * Images point at stable public paths served by the frontend (frontend/public/images).
 */

export const BANK_DETAILS = {
  bankName: "Bank of India · Salugara, Siliguri",
  accountName: "BTMC Foundation",
  accountNumber: "50782011000314",
  ifsc: "BKID0005078",
  branch: "Salugara, Siliguri",
};

export const events = [
  {
    slug: "delhi-healing-meditation-dharma",
    city: "New Delhi",
    country: "India",
    title: "Healing, Meditation, Dharma Discourse & Charity Event",
    tagline: "A special one-day spiritual gathering for healing, blessings & inner peace",
    status: "upcoming",
    detailsAvailable: true,
    date: "Saturday, 22 August 2026",
    dateShort: "22 Aug 2026",
    venue: "Constitution Club of India",
    venueNote: "Near Patel Chowk Metro Station, New Delhi",
    image: "/images/charity.jpg",
    teacher: "Venerable Dr. Khen Rinpoche Sonam Gyurme",
    teacherTitle: "Main Abbot and Chairman of BTMC Foundation India & Dharma Television Nepal",
    videoUrl: "https://www.youtube.com/embed/1ZYbU82GVz4",
    intro:
      "Join us for a special spiritual gathering to help overcome unknown and unresolved negative energies, physical and mental health challenges, and difficulties in your career, business, relationships, education, marriage and personal growth.",
    overview: [
      "Discover inner peace, confidence, clarity, spiritual guidance and a renewed sense of purpose through healing, meditation and the wisdom of the Dharma.",
      "Our special one-day charity event features two unique sessions — a Morning Healing & Meditation Session and an Afternoon Long-Life, Health, Fortune & Prosperity Blessing Ceremony with Dharma Discourse.",
      "Everyone is warmly welcome.",
    ],
    descriptionHtml: "",
    sessions: [
      {
        name: "Morning Healing & Meditation Session",
        time: "9:00 AM – 12:00 PM",
        tone: "Buddhist healing, purification & inner peace",
        donation: "₹1,500 (Lunch Included)",
        description:
          "Dedicated to supporting individuals experiencing stress, anxiety, persistent negative thoughts, emotional challenges and other mental and emotional well-being concerns. Through authentic Buddhist healing, teachings and spiritual practices, participants are guided toward greater inner peace, emotional balance and spiritual growth. It also welcomes those who feel affected by negative energies or inauspicious karmic influences and seek purification through Dharma practice.",
        highlights: [
          "Ancient Buddhist Healing Practices",
          "Spiritual Empowerment & Blessings",
          "Confession & Purification Practices",
          "Energy Transmission",
          "Guided Meditation & Group Prayers",
          "Compassion & Loving-Kindness Practice",
          "Generosity, Merit-Making & Practical Dharma Teachings",
          "FREE Five-Combined Protective Amulet, personally blessed by the Venerable Master",
        ],
      },
      {
        name: "Afternoon Blessing Ceremony & Dharma Discourse",
        time: "12:30 PM – 3:00 PM",
        tone: "Long Life, Health, Fortune & Prosperity blessings",
        donation: "₹1,000 (Tea & Snacks Included)",
        description:
          "Receive the blessings of Long Life, Good Health, Fortune, Prosperity and Inner Well-being from Venerable Dr. Khen Rinpoche Sonam Gyurme. This inspiring session is ideal for students, professionals, entrepreneurs, business owners, corporate leaders, job seekers, couples and families seeking wisdom and guidance for career, business, education, relationships, marriage, finances and personal growth.",
        highlights: [
          "Long Life, Health, Fortune & Prosperity Blessings",
          "Inspiring Dharma Talk with practical guidance for everyday life",
          "Teachings on self-confidence, emotional balance & ethical leadership",
          "Wise decision-making for career, business & family",
          "FREE Five-Combined Protective Amulet, personally blessed by the Venerable Master",
        ],
      },
    ],
    contacts: ["+91-8178804502", "+91-7065277012"],
    email: "info@btmcfoundation.in",
    website: "www.btmcfoundation.in",
    supportsNote:
      "Your generous contribution supports the upcoming Weekly 2-Day Free Meditation Retreat Program at Kathmandu, Nepal.",
    bank: BANK_DETAILS,
  },
  {
    slug: "mumbai-healing-charity",
    city: "Mumbai",
    country: "India",
    title: "Healing, Meditation & Charity Gathering",
    tagline: "Blessings, healing meditation and compassionate service by the sea",
    status: "past",
    detailsAvailable: false,
    date: "Completed 2025",
    dateShort: "2025",
    venue: "Mumbai, Maharashtra",
    venueNote: "India",
    image: "/images/meditation-retreat.jpg",
    teacher: "Venerable Dr. Khen Rinpoche Sonam Gyurme",
    teacherTitle: "Main Abbot and Chairman of BTMC Foundation India",
    videoUrl: "",
    intro:
      "A blessed gathering of healing, meditation and Dharma teaching that brought together practitioners from across western India.",
    overview: [
      "Participants received healing blessings, guided meditation and practical Dharma guidance for daily life.",
    ],
    descriptionHtml: "",
    sessions: [],
    contacts: ["+91-8178804502"],
    email: "info@btmcfoundation.in",
    website: "www.btmcfoundation.in",
    supportsNote: "Proceeds supported free meditation retreats and humanitarian programs.",
    bank: BANK_DETAILS,
  },
  {
    slug: "kolkata-healing-charity",
    city: "Kolkata",
    country: "India",
    title: "Healing, Meditation & Charity Gathering",
    tagline: "A day of purification, prayer and loving-kindness",
    status: "past",
    detailsAvailable: false,
    date: "Completed 2025",
    dateShort: "2025",
    venue: "Kolkata, West Bengal",
    venueNote: "India",
    image: "/images/peace-prayer.jpg",
    teacher: "Venerable Dr. Khen Rinpoche Sonam Gyurme",
    teacherTitle: "Main Abbot and Chairman of BTMC Foundation India",
    videoUrl: "",
    intro:
      "An inspiring gathering of Buddhist healing, meditation and compassion practice held in the heart of Kolkata.",
    overview: [
      "Participants experienced healing rituals, compassion practices and Dharma teachings for a calmer, more resilient mind.",
    ],
    descriptionHtml: "",
    sessions: [],
    contacts: ["+91-8178804502"],
    email: "info@btmcfoundation.in",
    website: "www.btmcfoundation.in",
    supportsNote: "Proceeds supported free meditation retreats and humanitarian programs.",
    bank: BANK_DETAILS,
  },
];

export const products = [
  {
    id: "am-1",
    category: "amulets",
    name: "Five-Combined Protective Amulet",
    blessing: "Personally blessed by the Venerable Master",
    price: "₹5,100",
    priceValue: 5100,
    rating: 5.0,
    reviews: 214,
    badge: "Most Sacred",
    description:
      "Our flagship Srungwa — a five-combined protective amulet prepared according to Buddhist astrology and tantra, uniting gold, silver, precious gemstones, sacred medicinal substances and powerful mantras. Personally consecrated and blessed by Venerable Dr. Khen Rinpoche Sonam Gyurme for protection, auspiciousness and the fulfilment of positive aspirations.",
    includes: [
      "Consecrated by the Venerable Master",
      "Gold & silver with gemstone",
      "Sacred medicinal substances",
      "Care & wearing guidance",
    ],
  },
  {
    id: "am-2",
    category: "amulets",
    name: "Personalized Yidam Amulet",
    blessing: "Crafted to your Lo, Kham, Parkha & Mewa",
    price: "₹11,000",
    priceValue: 11000,
    rating: 4.9,
    reviews: 96,
    badge: "Bespoke",
    description:
      "An individually prepared amulet based on your Marriage, Natal, Business and Planetary-Prediction astrology. Beautifully crafted in gold or silver with appropriate gemstones, containing a gold or coloured Thangka of your personal Yidam (meditational deity) and Auspicious Guardian Deity, combined with protective medicinal substances.",
    includes: [
      "Astrological consultation",
      "Personal Yidam Thangka",
      "Gold or silver casing",
      "Lifetime protection amulet",
    ],
  },
  {
    id: "tv-1",
    category: "treasure-vase",
    name: "Golden Treasure Vase (Terbum)",
    blessing: "Attracts wealth & abundance",
    price: "₹8,500",
    priceValue: 8500,
    rating: 4.8,
    reviews: 63,
    badge: "Consecrated",
    description:
      "A consecrated Treasure Vase filled with sacred substances, mantras and precious materials to attract prosperity, abundance and auspicious energy. Traditionally placed in the home, business or shrine to draw continuous wealth and blessings.",
    includes: ["Filled & sealed by monks", "Sacred wealth substances", "Placement guidance", "Consecration prayers"],
  },
  {
    id: "st-1",
    category: "statues",
    name: "Gilded Shakyamuni Buddha Statue",
    blessing: "Hand-finished & ready for consecration",
    price: "₹15,000",
    priceValue: 15000,
    rating: 5.0,
    reviews: 41,
    badge: "Handcrafted",
    description:
      "A finely crafted, hand-finished statue of Shakyamuni Buddha, suitable as the central image of a home or monastery shrine. Available for traditional filling and consecration (rabne) on request.",
    includes: ["Hand-finished gilding", "Optional consecration", "Shrine placement guidance", "Certificate of authenticity"],
  },
  {
    id: "th-1",
    category: "thangkas",
    name: "Medicine Buddha Thangka",
    blessing: "For healing & well-being",
    price: "₹9,800",
    priceValue: 9800,
    rating: 4.9,
    reviews: 58,
    badge: "Hand-painted",
    description:
      "A hand-painted Thangka of the Medicine Buddha, created by skilled artists using traditional mineral pigments and gold. A powerful support for healing practice, recovery and well-being — a sacred heirloom for your shrine.",
    includes: ["Traditional mineral pigments", "Gold detailing", "Brocade mounting option", "Ready to hang & practice"],
  },
  {
    id: "pd-1",
    category: "pendants",
    name: "Auspicious Guardian Pendant",
    blessing: "Wearable blessing & protection",
    price: "₹3,600",
    priceValue: 3600,
    rating: 4.8,
    reviews: 132,
    badge: "Bestseller",
    description:
      "An elegant silver pendant set with a sacred image of your Auspicious Guardian Deity (Lucky God) and a protective mantra. Beautifully crafted for comfortable daily wear and continuous blessing.",
    includes: ["Silver with sacred image", "Protective mantra inlay", "Adjustable cord", "Blessed before dispatch"],
  },
];
