/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SpiritualTripsRouteImport } from './routes/spiritual-trips'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegistrationSuccessRouteImport } from './routes/registration-success'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PeacePrayersRouteImport } from './routes/peace-prayers'
import { Route as OnlineClassesRouteImport } from './routes/online-classes'
import { Route as HealingItemsRouteImport } from './routes/healing-items'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DharmaCampaignRouteImport } from './routes/dharma-campaign'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharityEventsIndexRouteImport } from './routes/charity-events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CharityEventsSlugRouteImport } from './routes/charity-events.$slug'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminHealingItemsRouteImport } from './routes/admin.healing-items'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminCharityEventsRouteImport } from './routes/admin.charity-events'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiritualTripsRoute = SpiritualTripsRouteImport.update({
  id: '/spiritual-trips',
  path: '/spiritual-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSuccessRoute = RegistrationSuccessRouteImport.update({
  id: '/registration-success',
  path: '/registration-success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PeacePrayersRoute = PeacePrayersRouteImport.update({
  id: '/peace-prayers',
  path: '/peace-prayers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineClassesRoute = OnlineClassesRouteImport.update({
  id: '/online-classes',
  path: '/online-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const HealingItemsRoute = HealingItemsRouteImport.update({
  id: '/healing-items',
  path: '/healing-items',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DharmaCampaignRoute = DharmaCampaignRouteImport.update({
  id: '/dharma-campaign',
  path: '/dharma-campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharityEventsIndexRoute = CharityEventsIndexRouteImport.update({
  id: '/charity-events/',
  path: '/charity-events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CharityEventsSlugRoute = CharityEventsSlugRouteImport.update({
  id: '/charity-events/$slug',
  path: '/charity-events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealingItemsRoute = AdminHealingItemsRouteImport.update({
  id: '/healing-items',
  path: '/healing-items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCharityEventsRoute = AdminCharityEventsRouteImport.update({
  id: '/charity-events',
  path: '/charity-events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dharma-campaign': typeof DharmaCampaignRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/healing-items': typeof HealingItemsRoute
  '/online-classes': typeof OnlineClassesRoute
  '/peace-prayers': typeof PeacePrayersRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/services': typeof ServicesRoute
  '/spiritual-trips': typeof SpiritualTripsRoute
  '/sponsors': typeof SponsorsRoute
  '/support': typeof SupportRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/charity-events': typeof AdminCharityEventsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/healing-items': typeof AdminHealingItemsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/charity-events/$slug': typeof CharityEventsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/charity-events/': typeof CharityEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dharma-campaign': typeof DharmaCampaignRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/healing-items': typeof HealingItemsRoute
  '/online-classes': typeof OnlineClassesRoute
  '/peace-prayers': typeof PeacePrayersRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/services': typeof ServicesRoute
  '/spiritual-trips': typeof SpiritualTripsRoute
  '/sponsors': typeof SponsorsRoute
  '/support': typeof SupportRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/charity-events': typeof AdminCharityEventsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/healing-items': typeof AdminHealingItemsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/charity-events/$slug': typeof CharityEventsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/charity-events': typeof CharityEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dharma-campaign': typeof DharmaCampaignRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/healing-items': typeof HealingItemsRoute
  '/online-classes': typeof OnlineClassesRoute
  '/peace-prayers': typeof PeacePrayersRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/services': typeof ServicesRoute
  '/spiritual-trips': typeof SpiritualTripsRoute
  '/sponsors': typeof SponsorsRoute
  '/support': typeof SupportRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/charity-events': typeof AdminCharityEventsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/healing-items': typeof AdminHealingItemsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/charity-events/$slug': typeof CharityEventsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/charity-events/': typeof CharityEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dharma-campaign'
    | '/donate'
    | '/events'
    | '/healing-items'
    | '/online-classes'
    | '/peace-prayers'
    | '/projects'
    | '/register'
    | '/registration-success'
    | '/services'
    | '/spiritual-trips'
    | '/sponsors'
    | '/support'
    | '/admin/bookings'
    | '/admin/charity-events'
    | '/admin/donations'
    | '/admin/healing-items'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/team'
    | '/charity-events/$slug'
    | '/admin/'
    | '/charity-events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dharma-campaign'
    | '/donate'
    | '/events'
    | '/healing-items'
    | '/online-classes'
    | '/peace-prayers'
    | '/projects'
    | '/register'
    | '/registration-success'
    | '/services'
    | '/spiritual-trips'
    | '/sponsors'
    | '/support'
    | '/admin/bookings'
    | '/admin/charity-events'
    | '/admin/donations'
    | '/admin/healing-items'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/team'
    | '/charity-events/$slug'
    | '/admin'
    | '/charity-events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dharma-campaign'
    | '/donate'
    | '/events'
    | '/healing-items'
    | '/online-classes'
    | '/peace-prayers'
    | '/projects'
    | '/register'
    | '/registration-success'
    | '/services'
    | '/spiritual-trips'
    | '/sponsors'
    | '/support'
    | '/admin/bookings'
    | '/admin/charity-events'
    | '/admin/donations'
    | '/admin/healing-items'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/team'
    | '/charity-events/$slug'
    | '/admin/'
    | '/charity-events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DharmaCampaignRoute: typeof DharmaCampaignRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  HealingItemsRoute: typeof HealingItemsRoute
  OnlineClassesRoute: typeof OnlineClassesRoute
  PeacePrayersRoute: typeof PeacePrayersRoute
  ProjectsRoute: typeof ProjectsRoute
  RegisterRoute: typeof RegisterRoute
  RegistrationSuccessRoute: typeof RegistrationSuccessRoute
  ServicesRoute: typeof ServicesRoute
  SpiritualTripsRoute: typeof SpiritualTripsRoute
  SponsorsRoute: typeof SponsorsRoute
  SupportRoute: typeof SupportRoute
  CharityEventsSlugRoute: typeof CharityEventsSlugRoute
  CharityEventsIndexRoute: typeof CharityEventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spiritual-trips': {
      id: '/spiritual-trips'
      path: '/spiritual-trips'
      fullPath: '/spiritual-trips'
      preLoaderRoute: typeof SpiritualTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-success': {
      id: '/registration-success'
      path: '/registration-success'
      fullPath: '/registration-success'
      preLoaderRoute: typeof RegistrationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peace-prayers': {
      id: '/peace-prayers'
      path: '/peace-prayers'
      fullPath: '/peace-prayers'
      preLoaderRoute: typeof PeacePrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-classes': {
      id: '/online-classes'
      path: '/online-classes'
      fullPath: '/online-classes'
      preLoaderRoute: typeof OnlineClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healing-items': {
      id: '/healing-items'
      path: '/healing-items'
      fullPath: '/healing-items'
      preLoaderRoute: typeof HealingItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dharma-campaign': {
      id: '/dharma-campaign'
      path: '/dharma-campaign'
      fullPath: '/dharma-campaign'
      preLoaderRoute: typeof DharmaCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charity-events/': {
      id: '/charity-events/'
      path: '/charity-events'
      fullPath: '/charity-events/'
      preLoaderRoute: typeof CharityEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/charity-events/$slug': {
      id: '/charity-events/$slug'
      path: '/charity-events/$slug'
      fullPath: '/charity-events/$slug'
      preLoaderRoute: typeof CharityEventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/healing-items': {
      id: '/admin/healing-items'
      path: '/healing-items'
      fullPath: '/admin/healing-items'
      preLoaderRoute: typeof AdminHealingItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/charity-events': {
      id: '/admin/charity-events'
      path: '/charity-events'
      fullPath: '/admin/charity-events'
      preLoaderRoute: typeof AdminCharityEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCharityEventsRoute: typeof AdminCharityEventsRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminHealingItemsRoute: typeof AdminHealingItemsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCharityEventsRoute: AdminCharityEventsRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminHealingItemsRoute: AdminHealingItemsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DharmaCampaignRoute: DharmaCampaignRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  HealingItemsRoute: HealingItemsRoute,
  OnlineClassesRoute: OnlineClassesRoute,
  PeacePrayersRoute: PeacePrayersRoute,
  ProjectsRoute: ProjectsRoute,
  RegisterRoute: RegisterRoute,
  RegistrationSuccessRoute: RegistrationSuccessRoute,
  ServicesRoute: ServicesRoute,
  SpiritualTripsRoute: SpiritualTripsRoute,
  SponsorsRoute: SponsorsRoute,
  SupportRoute: SupportRoute,
  CharityEventsSlugRoute: CharityEventsSlugRoute,
  CharityEventsIndexRoute: CharityEventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
